# Generated by Django 2.1.3 on 2018-11-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troubleorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleorder',
            name='trouble_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='故障单号'),
        ),
    ]
